[package]
name = "collections"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
name = "collections"
path = "src/collections.rs"
doctest = false

[dependencies]
rustc-hash.workspace = true
indexmap.workspace = true

[lints]
workspace = true
