[package]
name = "humanssh_paths"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
name = "humanssh_paths"
path = "src/paths.rs"
doctest = false

[dependencies]
dirs.workspace = true

[lints]
workspace = true
