[package]
name = "actions"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lib]
path = "src/actions.rs"
doctest = false

[dependencies]
gpui.workspace = true

[lints]
workspace = true
